polls/polls/urls.py
# from django.conf.urls import include, url
from django.contrib import admin
#
# urlpatterns = [
#     url(r'^admin/', include(admin.site.urls)),
# ]

from django.conf.urls import patterns, include, url
from pollsApp.views import *

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', main),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', logout_page),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'), # If user is not login it will redirect to login page
    url(r'^register/$', register),
    url(r'^register/success/$', register_success),
    url(r'^home/$', home),
    url(r'^poll_add/$', PollCreate.as_view),
)

polls/pollsApp/models.py
from django.db import models
from django.contrib.auth.models import User


class Poll(models.Model):
    name = models.CharField(max_length=100)
    author = models.ForeignKey(User)
    votes = models.IntegerField(blank=True, null=True)
    weight = models.IntegerField(choices=[(i, i) for i in range(11)], default=10)

class Question(models.Model):
    question = models.TextField()
    votes = models.IntegerField(blank=True, null=True)
    poll = models.ForeignKey(Poll)

class Answer(models.Model):
    answer = models.TextField()
    votes = models.IntegerField(blank=True, null=True)
    question = models.ForeignKey(Question)

polls/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <title>Django Polls Application |
        {% block title %}{% endblock %}</title>
    </head>
    <body>
        <h1>{% block head %}{% endblock %}</h1>
        {% block content %}{% endblock %}
 
    </body>
</html>

polls/templates/home.html
{% extends "base.html" %}
{% block title %}Welcome to Polls!{% endblock %}
{% block head %}Welcome to Polls!{% endblock %}
{% block content %}

    <a href="/" style="font-size: 20px">MAIN PAGE</a> <span style="font-size: 20px">PERSONAL PAGE</span>

    <p>Welcome to your home page {{ user.username }} !!! <a href="/logout/">Logout</a></p>
<a href="/poll_add/">Create poll</a>

{% endblock %}

polls/templates/main.html
{% extends "base.html" %}
{% block title %}Welcome to Polls!{% endblock %}
{% block head %}Welcome to Polls!{% endblock %}
{% block content %}

    <span style="font-size: 20px">MAIN PAGE</span> <a href="/home/" style="font-size: 20px">PERSONAL PAGE</a>

    {% if user.username == "" %}
        <p>If you want to create polls or answer them, please <a href="/login/">Login</a></p>
    {% else %}
        <p>Welcome {{ user.username }} !!! <a href="/logout/">Logout</a></p>
    {% endif %}

    <h2>All polls</h2>
    {% for poll in polls %}
        <p>{{ poll.name }}</p>
    {% endfor %}

{% endblock %}

polls/templates/poll_add.html
{% extends "base.html" %}
{% block title %}Create your Poll!{% endblock %}
{% block head %}Create your Poll!{% endblock %}
{% block content %}

    {% if form.errors %}
        <p>Errors in form. Please try again.</p>
    {% endif %}
    <form method="post" action=".">{% csrf_token %}
        <table border="0">
            <tr><th><label for="id_name">Name:</label></th><td>{{ form.name }}</td></tr>
            <!--<tr><th><label for="id_author">Weight:</label></th><td>{{ form.weight }}</td></tr>-->
            <tr><th><label for="id_weight">Weight:</label></th><td>{{ form.weight }}</td></tr>
        </table>
        <input type="submit" value="Create" />
        <!--<input type="hidden" name="next" value="/home" />-->
    </form>

{% endblock %}